version: '2'
services:
    trivia-app:
        image: trivia
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trivia-mysql:3306/trivia?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trivia-mysql:
        extends:
            file: mysql.yml
            service: trivia-mysql
